apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-api-pod-v1
  labels:
    app: atlas-api-pod-v1
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: atlas-api-pod-v1
  template:
    metadata:
      labels:
        app: atlas-api-pod-v1
    spec:
      containers:
        - name: atlas-api-pod
          image: manthapavankumar11/docker-ninja:companies-api-v2
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-details
          securityContext:
            runAsUser: 1010


