apiVersion: v1
kind: ReplicationController
metadata:
  name: marvel-rc
  labels:
    zone: dev
    version: v2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: marvel-api-v2
    spec:
      containers:
        - name: marvel-pod
          image: <docker-image>
          ports:
          - containerPort: 3000
